security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: database_users
            custom_authenticator:
                - App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/operation, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_EXPERT }
        - { path: ^/profile, roles: ROLE_SENIOR }
        - { path: ^/profile, roles: ROLE_JUNIOR }
