controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

nave_route:
    path: /base/nave
    controller: 'App\Controller\YourController::yourAction'