controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


redirection_vue:
    path: /redirection
    controller: App\Controller\YourController::yourAction

login_vue:
    path: /Login
    controller: App\Controller\LoginController::login



# config/routes.yaml
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

confirmation:
    path: /confirmation
    controller: App\Controller\ConfirmationController::index

