controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# config/routes.yaml
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

confirmation:
    path: /confirmation
    controller: App\Controller\ConfirmationController::index
