controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
operation:
    path: /operation
    controller: App\Controller\OperationController::operation
