controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

redirection_vue:
    path: /redirection
    controller: App\Controller\YourController::yourAction

app_login:
    path: /login
    controller: App\Controller\LoginController::login

confirmation:
    path: /confirmation
    controller: App\Controller\ConfirmationController::index


generate_pdf:
    path: /pdf
    controller: App\Controller\PdfController::generatePdf




